#pragma config(Sensor, dgtl1,  dgtl01,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  ,               sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct{
	int x;
	int y;
	int yaw;
} pose;

task task1()
{
  while (1)
  {
  	wait1Msec(1000);
  }
}



task main()
{

	startTask(task1);
while (1){
		int x = SensorValue[dgtl01];
  }

}
